---
title: "Sociodem characteristics_v2"
author: "Josh Alampi"
date: "09/01/2023"
output: html_document
---


# load
```{r}
#clear workspace
rm(list=ls(all=TRUE))

#load packages
#load packages
library(readr); library(writexl) # for read_csv(); write_xlsx()  
library(plyr) # mapvalues()
library(MASS)
library(dplyr)
library(tidyr) # for gather()
# library(ggplot2)
# library(ggrepel); library(ggpubr); library(scales) # extra ggplot features
# library(signs) # for signs_format(), uses proper minus sign instead of hyphen
# library(lmtest) # for bptest()
# library(quantreg)
# library(bayesQR)
select <- dplyr::select
# library(rstan)
# library(emg) # for exponentially modified gaussian model

library(EnvStats)

data <- read.csv("//ais-fs1.sfu.ca/home2/Redirected_Profiles/jalampi/Desktop/MIREC loader 2022/clean data/2024-04-02_MIREC data.csv") 

```

# clean data

## rm participants
```{r}
data <- data %>% 
  filter(is.na(srs) == F)  #n = 601 mothers whose child had an SRS score. 
```


## make new variable: home.score2 (binary variable) 
```{r}
median_home <- quantile(data$home.score, 0.5, na.rm = T)
median_srs_age <- quantile(data$srs.age, 0.5)


data <- data %>% 
  mutate(home.score2 = ifelse(home.score >= median_home, 1, 0)) %>% # Make HOME score a binary variable
  mutate(srs.age2 = ifelse(srs.age >= median_srs_age, 1, 0)) %>% # Make SRS age a binary variable
  mutate(all = 1) # make a variable where all participants are coded as == 1. 

```

## make categorical plasma-folate variable
```{r}
# first trimester concentrations
# pl_fol_10.t1 <- 65.6
pl_fol_10.t1 <- quantile(data$tot_fol.t1, 0.1, na.rm = T)
# pl_fol_80.t1 <- 125
pl_fol_80.t1 <- quantile(data$tot_fol.t1, 0.8, na.rm = T)

data <- data %>% 
  mutate(pl_fol3.t1 = case_when(tot_fol.t1 < pl_fol_10.t1 ~ 1,
                                tot_fol.t1 >= pl_fol_10.t1 & tot_fol.t1 < pl_fol_80.t1 ~2,
                                tot_fol.t1 >= pl_fol_80.t1 ~ 3) )


# third trimester concentrations
pl_fol_10.t3 <- quantile(data$tot_fol.t3, 0.1, na.rm = T)
# pl_fol_10.t3 <- 49.3
pl_fol_80.t3 <- quantile(data$tot_fol.t3, 0.8, na.rm = T)
# pl_fol_80.t3 <- 158

data <- data %>% 
  mutate(pl_fol3.t3 = case_when(tot_fol.t3 < pl_fol_10.t3 ~ 1,
                                tot_fol.t3 >= pl_fol_10.t3 & tot_fol.t3 < pl_fol_80.t3 ~2,
                                tot_fol.t3 >= pl_fol_80.t3 ~ 3) )
```


#make function
```{r}
get_ds <- function(data, var, level, name, round = 1, roundchem = 2) {
  tot_n <- nrow(data)
  if(level == "NA"){
    subset_data <- filter(data, is.na({{var}}) == T)
  } else {
    subset_data <- filter(data, {{var}} == {{level}})
  }
  
  n <- nrow(subset_data)
  perc <- format(round(n/tot_n*100, round), nsmall = round)
  
  srs_mean <- format(round(mean(subset_data$srs), round), nsmall = round)
  srs_sd <-format(round(sd(subset_data$srs), round), nsmall = round)
  
  lead.t1_mean <- format(round(geoMean(subset_data$lead.t1.res, na.rm = T), roundchem), nsmall = roundchem)
  lead.t1_gsd <- format(round(geoSD(subset_data$lead.t1.res, na.rm = T), roundchem), nsmall = roundchem)
  
  lead.t3_mean <- format(round(geoMean(subset_data$lead.t3.res, na.rm = T), roundchem), nsmall = roundchem)
  lead.t3_gsd <- format(round(geoSD(subset_data$lead.t3.res, na.rm = T), roundchem), nsmall = roundchem)
  
  
  if(level == "NA"){
    srs_mean <- paste0("")
    srs_sd <-paste0("")
    
    lead.t1_mean <- paste0("")
    lead.t1_gsd <- paste0("")
    lead.t3_mean <- paste0("")
    lead.t3_gsd <- paste0("")

  }
  
  mat <- matrix(data=NA, nrow = 1, ncol = 9)
  mat[1,1] <- (paste0("   ", name))
  mat[1,2] <- n; mat[1,3] <- perc
  mat[1,4] <- srs_mean; mat[1,5] <- srs_sd
  
  mat[1,6] <- lead.t1_mean; mat[1,7] <- lead.t1_gsd
  mat[1,8] <- lead.t3_mean; mat[1,9] <- lead.t3_gsd
  
  
  return(mat)
}
```

test:
```{r}
get_ds(data, sex2, 0, "Male")
```

# make table
```{r}
table1 <- setNames(data.frame(matrix(data = NA, nrow = 65, ncol = 9)), #make dataframe
                              c("Variable", "n", "(%)", "Mean SRS", "SRS SD", 
                                "lead.t1_mean", "lead.t1_gsd", "lead.t3_mean", "lead.t3_gsd")) #set column names
```

# populate
```{r}
i <- 1

table1[i,] <- get_ds(data, all, 1, "Total"); i <- i + 1

table1[i,1] <- "Child sex"; i <- i + 1
table1[i,] <- get_ds(data, sex2, 0, "Male"); i <- i + 1
table1[i,] <- get_ds(data, sex2, 1, "Female"); i <- i + 1

table1[i,1] <- "Maternal age at enrollment"; i <- i + 1
table1[i,] <- get_ds(data, mom.age3, 1, "18 - 29"); i <- i + 1
table1[i,] <- get_ds(data, mom.age3, 2, "30 - 35"); i <- i + 1
table1[i,] <- get_ds(data, mom.age3, 3, "≥36"); i <- i + 1

table1[i,1] <- "Living with spouse"; i <- i + 1
table1[i,] <- get_ds(data, living.status2, 0, "Yes"); i <- i + 1
table1[i,] <- get_ds(data, living.status2, 1, "No"); i <- i + 1

table1[i,1] <- "Maternal race"; i <- i + 1
table1[i,] <- get_ds(data, race.white2, 1, "White"); i <- i + 1
table1[i,] <- get_ds(data, race.white2, 0, "Other"); i <- i + 1

table1[i,1] <- "Education level"; i <- i + 1
table1[i,] <- get_ds(data, edu4, 1, "High school or less"); i <- i + 1
table1[i,] <- get_ds(data, edu4, 2, "College or trade school"); i <- i + 1
table1[i,] <- get_ds(data, edu4, 3, "Undergraduate university degree"); i <- i + 1
table1[i,] <- get_ds(data, edu4, 4, "Graduate university degree"); i <- i + 1
table1[i,] <- get_ds(data, edu4, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Annual household income ($CAD)"; i <- i + 1
table1[i,] <- get_ds(data, income4, 1, "≤$40,000"); i <- i + 1
table1[i,] <- get_ds(data, income4, 2, "$40,001 - $80,000"); i <- i + 1
table1[i,] <- get_ds(data, income4, 3, "$80,001 - $100,000"); i <- i + 1
table1[i,] <- get_ds(data, income4, 4, ">$100,000"); i <- i + 1
table1[i,] <- get_ds(data, income4, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Parity"; i <- i + 1
table1[i,] <- get_ds(data, parity3, 1, "Nulliparous"); i <- i + 1
table1[i,] <- get_ds(data, parity3, 2, "Uniparous"); i <- i + 1
table1[i,] <- get_ds(data, parity3, 3, "Multiparous"); i <- i + 1

table1[i,1] <- "HOME score"; i <- i + 1
table1[i,] <- get_ds(data, home.score2, 1, "≥48 (median)"); i <- i + 1
table1[i,] <- get_ds(data, home.score2, 0, "<48 (median)"); i <- i + 1
table1[i,] <- get_ds(data, home.score2, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Smoked during pregnancy"; i <- i + 1
table1[i,] <- get_ds(data, smoker2, 1, "Yes"); i <- i + 1
table1[i,] <- get_ds(data, smoker2, 0, "No"); i <- i + 1

table1[i,1] <- "Year of enrollment"; i <- i + 1
table1[i,] <- get_ds(data, year.enroll4, 2008, "2008"); i <- i + 1
table1[i,] <- get_ds(data, year.enroll4, 2009, "2009"); i <- i + 1
table1[i,] <- get_ds(data, year.enroll4, 2010, "2010"); i <- i + 1
table1[i,] <- get_ds(data, year.enroll4, 2011, "2011"); i <- i + 1

table1[i,1] <- "Child age at SRS assessment"; i <- i + 1
table1[i,] <- get_ds(data, srs.age2, 1, "≥40 months (median)"); i <- i + 1
table1[i,] <- get_ds(data, srs.age2, 0, "<40 months (median)"); i <- i + 1

table1[i,1] <- "Folic acid supplementation (12-16 weeks' gestation)"; i <- i + 1
table1[i,] <- get_ds(data, fol.intake3, 1, "<400 µg per day"); i <- i + 1
table1[i,] <- get_ds(data, fol.intake3, 2, "400 - 1000 µg per day"); i <- i + 1
table1[i,] <- get_ds(data, fol.intake3, 3, ">1000 µg per day"); i <- i + 1
table1[i,] <- get_ds(data, fol.intake3, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Plasma total folate concentrations (first trimester)"; i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t1, 1, "<10ᵗʰ percentile (65.6 nmol/L)"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t1, 2, "10ᵗʰ - 80ᵗʰ percentile"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t1, 3, "≥80ᵗʰ percentile (125 nmol/L)"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t1, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Plasma total folate concentrations (third trimester)"; i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t3, 1, "<10ᵗʰ percentile (49.3 nmol/L)"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t3, 2, "10ᵗʰ - 80ᵗʰ percentile"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t3, 3, "≥80ᵗʰ percentile (158 nmol/L)"); i <- i + 1
table1[i,] <- get_ds(data, pl_fol3.t3, "NA", "Missing"); i <- i + 1

table1[i,1] <- "Maternal MTHFR 677 C>T genotype"; i <- i + 1
table1[i,] <- get_ds(data, mthfr677_cat, "C|C", "C|C"); i <- i + 1
table1[i,] <- get_ds(data, mthfr677_cat, "C|T", "C|T"); i <- i + 1
table1[i,] <- get_ds(data, mthfr677_cat, "T|T", "T|T"); i <- i + 1
table1[i,] <- get_ds(data, mthfr677_cat, "NA", "Missing"); i <- i + 1


i

```


# save
```{r}
table1 <- as.data.frame(table1)
#save as a MS excel file
write_xlsx(table1, path = paste0("descriptive stats/results/table_sociodem", "_",  Sys.Date(), ".xlsx", sep = ""))

```

```{r}

```

